name: Deploy node application

on:
  build:
    branches:
      - raji

jobs:
  build:
    runs-on: Ubuntu 24.04 LTS
  steps:
    - name: checkout source
      uses: actions/checkout@v4
    - name: login to docker hub
      uses: docker login -u 'sucessraji@gmail.com' -p 'raji@123kiot'
    - name: Build Docker image
      run: docker build -t rajeswaripoongodi/node-app .
    - name: Push Docker image to Docker Hub
        run: docker push rajeswaripoongodi/node-app:latest

  deploye:
    needs:  build
    runs-on: node-action
    steps:
      - name: Pull image from Docker Hub
        run: docker pull rajeswaripoongodi/node-app:latest
      - name: Run Docker container
        run: docker run --name node-app-container -p 4000:4000 -d rajeswaripoongodi/node-app:latest
